### PR TITLE
Added Flora, Leveled Items, Weapons, Item locations

### PR DESCRIPTION
**Pull request by Wully616**

### CODE REVIEW

**Comment by fwdekker** [comment]
Thank you for the PR, Wully! I'll take a look at it later today.

**Comment by fwdekker** [comment]
I like the flora, lvli, and weapons exports; they're very useful. I'm not sure if the locations export is necessary because I think that [map76](https://map76.com/) provides a much better way of accessing that data. What do you think?

**Comment by Wully616** [comment]
Does map76 provide a rest api or something to get the location data? I can only see that they just have the locations on a map
I'm creating a 3D pointcloud map and need the location data to basically do the same thing as map76 but in 3D - https://gfycat.com/honorablewellgroomedbabirusa

I can update the PR and move the location extraction into their own files, so they are separate from the flora, lvli and weapon exports?

**Comment by fwdekker** [comment]
Ah I see. In that case these exports would be very useful. Once you complete that 3d map, please let me know, it sounds really cool!

As for the files, yes, I would appreciate it if you could separate the location code to its own file. A single file for all five types should be fine; I just think it's nice to keep the code separated. Then you could also move the associated functions that are currently in the core to that file.

Any idea how large the location files will be if you export all records?

**Comment by Wully616** [comment]
Ok, I will move them to a seperate file along with functions for it.

The location files are a bit bigger than the normal data, but not huge

```
ARMORLOC:	823 KB
FLORALOC:	10,642 KB
LVLILOC:	19,272 KB
MISCLOC:	15,821 KB
WEAPLOC:	139 KB
```

**Comment by fwdekker** [comment]
Thanks!

Those sizes look fine. I was worried that we might have to split them up like with the ID files, but these aren't much bigger than some of the others. 👍

**Comment by fwdekker** [comment]
Have you been able to separate the location code into a separate file? Is there anything I can help with?

**Comment by Wully616** [comment]
I've not had time to work on it recently, i'll close the PR for now until I sort it. Shouldn't be any trouble with it

**Comment by fwdekker** [comment]
I have some time to work on this, so I'll see what I can do to implement these features.

**Comment by fwdekker** [comment]
Awesome! The logic of your code is mostly untouched; most changes were renaming and shuffling bits of code. I've also added a few extra fields here and there. Either way, thanks very much for this PR! I've added you to the credits section of the README :)

**Comment by Wully616** [comment]
Nice one! Apologies I never got round to it. Well done for taking it forward!

**Comment by fwdekker** [comment]
[v2.4.0 has been released](https://github.com/FWDekker/fo76-dumps/releases/tag/v2.4.0-v1.4.0.20) and now include the dumps from this PR

**Pull request merged**
